### ISSUE TITLE
Data preparation task list

### ISSUE THREAD

**Issue by darinddv** [darinddv/Hi-C-Loop-Prediction#2]
- [x] Align CTCF to x and y loop anchors
- [x] align chromatin compartments to x and y anchors

Design Matrix

- [ ] Set a categorical Y variable to 1 for all loop rows
- [ ] Create a dataframe of all non-loop genomic sequences of the proper lengths for all chromosomes to act as null cases
    - This is all possible non-loop sequences, so both the x and y anchors could be drawn from this
- [ ] Find average loop length from end of x2 to beginning of y1.
